[package]
name = "ddmw-types"
version = "0.1.1"
authors = ["Jan Danielsson <jan.danielsson@qrnch.com>"]
edition = "2018"
license = "0BSD"
keywords = [ "ddmw" ]
repository = "https://github.com/openqrnch/ddmw-types"
description = "Library with some basic DDMW types."

[dependencies]
